## KNN

import pandas dan numpy

In [1]:
import pandas as pd
import numpy as np

memasukkan data csv

In [11]:
data = pd.read_csv("https://raw.githubusercontent.com/UswatunChasanah/dataminingbaru/gh-pages/Data%20UTS.csv")
data.head(1000)

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  Classification  
0     7.99585  417.114               1  
1     4.06405  468.786               1  
2     9.27715  554.697               1  
3    12.76600  928.220               1  
4    10.57635  773.920               1  
..        ...      ...             ...  
111  10.96000  268.230               2  
112   7.32000  330.160               2  
113  10.33000  314.050               2  
114   3.27000  392.460               2  
115   4.35000   90.090               2  

[116 rows x 10 columns]

melihat tipe data yang akan digunakan

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             116 non-null    int64  
 1   BMI             116 non-null    float64
 2   Glucose         116 non-null    int64  
 3   Insulin         116 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          116 non-null    float64
 6   Adiponectin     116 non-null    float64
 7   Resistin        116 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    int64  
dtypes: float64(7), int64(3)
memory usage: 9.2 KB


menentukkan variable-variabel independennya yaitu age, BMI, Glucose, Insulin, HOMA, Leptin, Adiponectin, Resistin, dan MCP.1. Oleh karena itu variable Classification dikeluarkan.

In [12]:
x = data.drop(["Classification"], axis = 1)
x.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  
0  417.114  
1  468.786  
2  554.697  
3  928.220  
4  773.920

menentukkan variable dependennya yaitu Classification.

In [14]:
y = data["Classification"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Classification, dtype: int64

 mengimport package model selection dari SKlearn

In [29]:
from sklearn.model_selection import train_test_split

membagi data training dan data testing. Data training digunakan oleh algoritma klasifikasi. Memisahkan data menjadi training dan testing set dimaksudkan agar model yang diperoleh nantinya memiliki kemampuan generalisasi yang baik dalam melakukan klasifikasi data.

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

Mengaktifkan package StandardScaler dari SKlearn dan menuliskan syntax untuk mengubah skala data.

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

mengaktifkan package untuk klasifikasi KNN dengan mengimport package KNeighbors dari SKlearn

In [20]:
from sklearn.neighbors import KNeighborsClassifier

mengaktifkan fungsi klasifikasi untuk KNN

In [21]:
knn = KNeighborsClassifier (n_neighbors=4)

memasukkan data training pada fungsi klasifikasi untuk KNN

In [22]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

selanjutnya yaitu kita menentukkan prediksi atau peramalannya

In [23]:
y_pred = knn.predict(x_test)
y_pred

array([1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1,
       2, 2])

menentukkan probabilitas dari prediksi

In [30]:
knn.predict_proba(x_test)

array([[0.5 , 0.5 ],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.25, 0.75]])

import package untuk melihat keakuratan data hasil prediksi dengan data aktualnya

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

menampilakan matriks hasil prediksinya

In [27]:
print(confusion_matrix(y_test, y_pred))

[[9 2]
 [4 9]]


mengukur ketepatan atau keakuratan hasil prediksi

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.69      0.82      0.75        11
           2       0.82      0.69      0.75        13

    accuracy                           0.75        24
   macro avg       0.76      0.76      0.75        24
weighted avg       0.76      0.75      0.75        24

